### ISSUE TITLE
Outlook not working

### ISSUE THREAD

**Issue by Xornop** [ljmerza/ha-email-sensor#39]
I can't get outlook to work. It seems that it doesn't recognize "inbox" as an inbox. Nor "junkemail". I don't know which name to use for the main inbox, nor a custom folder (which would be my preferred option)
My email ends in hotmail.com.

```
- Logger: homeassistant.components.sensor
Source: custom_components/email/sensor.py:254
Integration: Sensor (documentation, issues)
First occurred: 00:15:45 (1 occurrences)
Last logged: 00:15:45

email: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/imaplib.py", line 1006, in _command
    self.send(data + CRLF)
  File "/usr/local/lib/python3.10/site-packages/imapclient/tls.py", line 62, in send
    self.sock.sendall(data)
  File "/usr/local/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/usr/local/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2396)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/email/sensor.py", line 254, in update
    server.logout()
  File "/usr/local/lib/python3.10/site-packages/imapclient/imapclient.py", line 513, in logout
    typ, data = self._imap.logout()
  File "/usr/local/lib/python3.10/imaplib.py", line 642, in logout
    typ, dat = self._simple_command('LOGOUT')
  File "/usr/local/lib/python3.10/imaplib.py", line 1230, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.10/imaplib.py", line 1008, in _command
    raise self.abort('socket error: %s' % val)
imaplib.IMAP4.abort: socket error: EOF occurred in violation of protocol (_ssl.c:2396)

```
but before that this also poppes up:
```
This error originated from a custom integration.

Logger: custom_components.email.sensor
Source: custom_components/email/sensor.py:220
Integration: email (documentation)
First occurred: 00:29:28 (1 occurrences)
Last logged: 00:29:28

IMAPClient update error: FETCH command error: BAD [b'Command Error. 10']
```

Version of the custom_component: 3.0.0
Configuration of sensors.yaml
```
  - platform: email
    email: **************@hotmail.com
    password: *******************
    imap_server: "imap-mail.outlook.com"
    folder: INBOX
```

**Comment by ljmerza** [comment]
best to post problems here https://community.home-assistant.io/t/home-assistant-email-sensor-with-tracking-number-scraping/112777
